name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run Your Build Script
      run: |
    - name: Conditional Job 1
      run: echo "This is Job 1"   
    - name: Sleep for 10 seconds
      run: sleep 10
